# -*- coding: utf-8 -*-
"""Abaqus API introspection script for the GUI_Abaqus reliability review
(Phase 1, _review/REVIEW.md).

WHY THIS SCRIPT EXISTS
-----------------------
The review of abaqus_scripts/cel_model.py and abaqus_scripts/cel_results.py
inventories every Abaqus Scripting Interface symbol the project relies on
(classes, methods, keyword arguments, symbolic constants). None of it could
be verified against a real Abaqus installation from the review environment
(no Abaqus available there — see REVIEW.md, "Vérification introspective").

This script performs a best-effort, read-only check of each symbol's
EXISTENCE and (where introspectable) call signature on the ACTUAL Abaqus
install it runs against. It does NOT build a model or run anything; it only
imports the relevant modules and uses hasattr()/dir()/inspect to check that
each name used by cel_model.py / cel_results.py is really there.

Existence alone does not prove correct usage (argument names, valid value
combinations, and behavioural semantics are NOT checked here) — treat a
"FOUND" row as necessary, not sufficient, evidence. Cross-check the keyword
arguments printed against the Abaqus Scripting Reference Guide.

USAGE (on the Abaqus PC, in a working directory you don't mind writing a
small text report into):

    abaqus cae noGUI=_review/check_api.py

Never run this from the production abaqus_scripts/ directory. It writes
"_review/check_api_report.txt" (relative to the CURRENT working directory
Abaqus was launched from) and touches nothing else.

This script is Python 2.7 (Abaqus 2022 HF8's bundled interpreter) — same
constraints as abaqus_scripts/*.py: no f-strings, no type annotations.
"""
import inspect
import sys


REPORT_LINES = []


def log(line=""):
    REPORT_LINES.append(line)
    print(line)


def check_attr(owner, owner_name, attr_name):
    """Report whether `owner.attr_name` exists, and its signature if it is
    introspectable (a function/method/class)."""
    ok = hasattr(owner, attr_name)
    if not ok:
        log("  [MISSING] %s.%s" % (owner_name, attr_name))
        return False
    obj = getattr(owner, attr_name)
    sig = ""
    try:
        if inspect.isfunction(obj) or inspect.ismethod(obj):
            sig = str(inspect.getargspec(obj))
        elif inspect.isclass(obj):
            init = getattr(obj, "__init__", None)
            if init is not None:
                try:
                    sig = str(inspect.getargspec(init))
                except TypeError:
                    sig = "(builtin/extension type — no introspectable signature)"
    except TypeError:
        sig = "(no introspectable signature)"
    log("  [FOUND]   %s.%s %s" % (owner_name, attr_name, sig))
    return True


def check_const(module, module_name, name):
    ok = hasattr(module, name)
    if ok:
        log("  [FOUND]   %s.%s = %r" % (module_name, name, getattr(module, name)))
    else:
        log("  [MISSING] %s.%s" % (module_name, name))
    return ok


def section(title):
    log("")
    log("=" * 78)
    log(title)
    log("=" * 78)


def main():
    log("Abaqus API introspection report")
    log("Generated by _review/check_api.py")
    try:
        log("Python: %s" % sys.version)
    except Exception:
        pass

    # -- abaqus / abaqusConstants -----------------------------------------
    section("import abaqus, abaqusConstants")
    try:
        import abaqus
        import abaqusConstants
    except Exception as exc:
        log("[FATAL] cannot import abaqus/abaqusConstants: %s" % exc)
        _write_report()
        return

    check_attr(abaqus, "abaqus", "mdb")
    mdb = abaqus.mdb
    check_attr(mdb, "mdb", "Model")
    check_attr(mdb, "mdb", "Job")

    log("")
    log("-- abaqusConstants used by cel_model.py / cel_results.py --")
    const_names = [
        "THREE_D", "EULERIAN", "DEFORMABLE_BODY", "OFF", "ON",
        "EC3D8RT", "C3D8RT", "EXPLICIT", "DEFAULT", "HEX", "STRUCTURED",
        "SWEEP", "SINGLE", "PENALTY", "ROUGH", "FRICTIONLESS", "HARD",
        "EXPONENTIAL", "LINEAR", "TABULAR", "GLOBAL", "SELF",
        "JOHNSON_COOK", "CONSTANTPRESSURE", "ENERGY",  # ENERGY: damage evol., commented out in code
        "MAGNITUDE", "SET", "FREE", "NONE", "VOID", "NON_REFLECTING",
        "EQUILIBRIUM", "ZERO_PRESSURE", "INFLOW", "OUTFLOW", "BOTH",
        "ANALYSIS", "DOUBLE", "FULL", "CENTROID", "NODAL", "MISES",
        "PRESS", "PRESELECT",
    ]
    for name in const_names:
        check_const(abaqusConstants, "abaqusConstants", name)

    # -- sketch --------------------------------------------------------
    section("import sketch — ConstrainedSketch methods used")
    try:
        import sketch
        # ConstrainedSketch itself lives on model.ConstrainedSketch(); check
        # the methods used on an instance via the class if importable.
        cls = getattr(sketch, "ConstrainedSketch", None)
        if cls is None:
            log("  [MISSING] sketch.ConstrainedSketch")
        else:
            for m in ("rectangle", "Spot", "FixedConstraint", "Line",
                      "HorizontalConstraint", "VerticalConstraint",
                      "FilletByRadius", "CoincidentConstraint",
                      "ObliqueDimension", "AngularDimension"):
                check_attr(cls, "ConstrainedSketch", m)
    except Exception as exc:
        log("[ERROR] sketch introspection failed: %s" % exc)

    # -- part ------------------------------------------------------------
    section("import part — Part methods used")
    try:
        import part
        cls = getattr(part, "Part", None)
        if cls is None:
            log("  [MISSING] part.Part")
        else:
            for m in ("BaseSolidExtrude", "SectionAssignment"):
                check_attr(cls, "Part", m)
    except Exception as exc:
        log("[ERROR] part introspection failed: %s" % exc)

    # -- regionToolset -----------------------------------------------------
    section("import regionToolset — Region used")
    try:
        import regionToolset
        check_attr(regionToolset, "regionToolset", "Region")
    except Exception as exc:
        log("[ERROR] regionToolset introspection failed: %s" % exc)

    # -- mesh --------------------------------------------------------------
    section("import mesh — ElemType used")
    try:
        import mesh
        check_attr(mesh, "mesh", "ElemType")
        et = getattr(mesh, "ElemType", None)
        if et is not None:
            try:
                log("  ElemType.__init__ %s"
                    % str(inspect.getargspec(et.__init__)))
            except Exception:
                log("  (ElemType.__init__ not introspectable — extension type)")
    except Exception as exc:
        log("[ERROR] mesh introspection failed: %s" % exc)

    # -- Model methods used (model.Xxx(...)) --------------------------------
    section("Model methods used by cel_model.py (via mdb.Model)")
    try:
        model_cls = None
        # abaqus.mdb.Model is a bound factory; the returned object's type is
        # Model in the `mdb` module namespace in real Abaqus. Try both.
        import mdb as mdb_module  # noqa: F401  (may not exist as top-level)
    except Exception:
        mdb_module = None
    # Best-effort: build nothing, just check Model class methods if
    # reachable through abaqus.mdb.models factory typing (varies by version).
    model_methods = [
        "ConstrainedSketch", "Part", "Material", "EulerianSection",
        "HomogeneousSolidSection", "ContactProperty", "ContactExp",
        "RigidBody", "TempDisplacementDynamicsStep", "ButterworthFilter",
        "FieldOutputRequest", "HistoryOutputRequest", "EulerianBC",
        "VelocityBC", "Velocity", "MaterialAssignment", "Temperature",
        "rootAssembly",
    ]
    log("  NOTE: Model is normally only reachable via mdb.Model(...); no "
        "static class introspection path is guaranteed across Abaqus "
        "versions. If the block above shows [MISSING] for any of these, "
        "cross-check manually with:")
    log("    m = mdb.Model(name='_check_api_tmp')")
    log("    [hasattr(m, x) for x in %r]" % model_methods)
    log("    del mdb.models['_check_api_tmp']")

    # -- Material methods --------------------------------------------------
    section("Material methods used (Density, Elastic, Plastic, ...)")
    try:
        import material
        cls = getattr(material, "Material", None)
        if cls is None:
            log("  [MISSING] material.Material")
        else:
            for m in ("Density", "Elastic", "Conductivity", "SpecificHeat",
                      "Expansion", "InelasticHeatFraction", "Plastic",
                      "JohnsonCookDamageInitiation"):
                check_attr(cls, "Material", m)
    except Exception as exc:
        log("[ERROR] material introspection failed: %s" % exc)

    # -- odbAccess -----------------------------------------------------------
    section("import odbAccess — extraction API used by cel_results.py")
    try:
        import odbAccess
        check_attr(odbAccess, "odbAccess", "openOdb")
    except Exception as exc:
        log("[ERROR] odbAccess introspection failed: %s" % exc)

    # -- CLI: abaqus help (best-effort; not run automatically) --------------
    section("CLI options used (abaqus terminate / job=... continue)")
    log("  NOT checked here: verify with 'abaqus help' / 'abaqus -help' on")
    log("  the command line directly. This script only checks the Python")
    log("  Scripting Interface, not the abq launcher's CLI surface.")
    log("  Commands used by the GUI (see REVIEW.md inventory table):")
    log("    abaqus cae noGUI=<script> -- --model_cfg <repr> --run_cfg <repr>")
    log("    abaqus terminate job=<name>")
    log("    abaqus job=<name> continue cpus=<n>")

    _write_report()


def _write_report():
    try:
        f = open("_review/check_api_report.txt", "w")
    except Exception:
        # Fall back to the current directory if _review/ doesn't exist here
        # (e.g. Abaqus was launched from elsewhere).
        f = open("check_api_report.txt", "w")
    try:
        f.write("\n".join(REPORT_LINES))
        f.write("\n")
    finally:
        f.close()
    print("")
    print("Report written.")


if __name__ == "__main__":
    main()
